baseURL = "https://www.selbram.org"
title = "Selbram"
theme = "m10c"
paginate = 5

[params]
  author = "Selbram"
  description = "Long-time gamer and new content creator."
  avatar = "selbram-avatar.jpg"
  
#[[params.social]]
#    name = "facebook"
#    url = "https://www.facebook.com/tory.starleaflabs"

[[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UChZL0mr0yXC8h8m2CxTIfBg"

[[params.social]]
    name = "twitter"
    url = "https://twitter.com/RealSelbram"




